######################################################
#                    DATABASE                        #
######################################################

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    run: mysql
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      run: mysql
  template:
    metadata:
      labels:
        run: mysql
        app: webshop
        version: "5.7.9"
    spec:
      containers:
      - image: docker.io/saigyouu/web-shop-db-image:latest
        name: web-shop-db-image
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: databasesecret
              key: mysqlrootpassword
        - name: MYSQL_PRODUCTS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: databasesecret
              key: mysqlproductspassword
        - name: MYSQL_CATEGORIES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: databasesecret
              key: mysqlcategoriespassword
        - name: MYSQL_WEBSHOPUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: databasesecret
              key: mysqlwebshopuserpassword
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

---

apiVersion: v1
kind: Secret
metadata:
  name: databasesecret
  namespace: default
stringData:
  mysqlrootpassword: c8de110f37300a53a971749
  mysqlproductspassword: 240b2c6d58ff2ce2f508b49f
  mysqlcategoriespassword: eitooPhah4oosh2Eegh5xooy
  mysqlwebshopuserpassword: Ako6ieveeDoob7eeBah2lee2

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: mysql
    app: webshop
  name: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql

---

######################################################
#                    PRODUCT                         #
######################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: product
  name: product
spec:
  replicas: 3
  selector:
    matchLabels:
      run: product
  template:
    metadata:
      labels:
        run: product
        app: webshop 
        version: "1.0"
    spec:
      containers:
      - image: docker.io/saigyouu/product:latest
        name: product
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: product-conf
              key: spring-datasource-url
        - name: CATEGORYSERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: product-conf
              key: category-service-url
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: product-conf
              key: server-port
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: product-conf
              key: spring-datasource-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: databasesecret
              key: mysqlproductspassword
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: product-conf
data:
  spring-datasource-url: "jdbc:mysql://mysql:3306/productsdb" 
  category-service-url: "http://category:8082"
  server-port: "8080"
  spring-datasource-username: productuser

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: product
    app: webshop
  name: product
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    run: product

---

######################################################
#                    CATEGORY                        #
######################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: category
  name: category
spec:
  replicas: 3
  selector:
    matchLabels:
      run: category
  template:
    metadata:
      labels:
        run: category
        app: webshop 
        version: "1.0"
    spec:
      containers:
      - image: docker.io/saigyouu/category:latest
        name: category
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: category-conf
              key: spring-datasource-url
        - name: PRODUCTSERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: category-conf
              key: product-service-url
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: category-conf
              key: server-port
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: category-conf
              key: spring-datasource-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: databasesecret
              key: mysqlcategoriespassword       
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: category-conf
data:
  spring-datasource-url: "jdbc:mysql://mysql:3306/categoriesdb" 
  product-service-url: "http://product:8081"
  server-port: "8080"
  spring-datasource-username: categoryuser

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: category
    app: webshop
  name: category
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8080
  selector:
    run: category

---

######################################################
#                    LEGACY                          #
######################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: legacywebshop
  name: legacywebshop
spec:
  replicas: 1
  selector:
    matchLabels:
      run: legacywebshop
  template:
    metadata:
      labels:
        run: legacywebshop
        app: webshop 
        version: "1.0"
    spec:
      containers:
      - image: docker.io/saigyouu/legacywebshop:latest
        name: legacywebshop
        env:
        - name: PRODUCTSERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: webshop-conf
              key: product-service-url
        - name: CATEGORYSERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: webshop-conf
              key: category-service-url
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: webshop-conf
data:
  product-service-url: "http://category:8081"
  category-service-url: "http://category:8082"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: legacywebshop
    app: webshop
  name: legacywebshop
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8080
  selector:
    run: legacywebshop

---

######################################################
#                    APACHE                          #
######################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: apache
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      run: apache
  template:
    metadata:
      labels:
        run: apache
    spec:
      containers:
      - image: docker.io/saigyouu/apache:latest
        imagePullPolicy: Always
        name: apache
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: apache
  name: apache
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: apache
  type: LoadBalancer
