version: '3.2'
services:
  legacywebshop:
    image: docker.io/saigyouu/legacywebshop:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8080"
    environment:
      - PRODUCTSERVICE_URL=http://product:8081
      - CATEGORYSERVICE_URL=http://category:8082
    networks:
      local_dev_net:
          aliases:
              - legacywebshop

  web-shop-db-image:
      image: docker.io/saigyouu/web-shop-db-image:latest
      build:
        context: ./
        dockerfile: ./docker/DockerfileMySQL
      volumes:
        - "./.data/db:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
        MYSQL_PRODUCTS_PASSWORD: 240b2c6d58ff2ce2f508b49f
        MYSQL_CATEGORIES_PASSWORD: eitooPhah4oosh2Eegh5xooy
        MYSQL_WEBSHOPUSER_PASSWORD: Ako6ieveeDoob7eeBah2lee2
        # MYSQL_USER: webshopuser
        # MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
      ports:
        - "3306:3306"
      networks:
          local_dev_net:
              aliases:
                  - web-shop-db-image

  product:
    image: docker.io/saigyouu/product:latest
    depends_on:
      - web-shop-db-image
    build:
      context: ./
      dockerfile: ./docker/DockerfileProduct
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://web-shop-db-image:3306/productsdb
      - CATEGORYSERVICE_URL=http://category:8082
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_USERNAME=productuser
      - SPRING_DATASOURCE_PASSWORD=240b2c6d58ff2ce2f508b49f
    ports:
      - "8081:8081"
    networks:
      local_dev_net:
          aliases:
              - product

  category:
    image: docker.io/saigyouu/category:latest
    depends_on:
      - web-shop-db-image
    build:
      context: ./
      dockerfile: ./docker/DockerfileCategory
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://web-shop-db-image:3306/categoriesdb
      - PRODUCTSERVICE_URL=http://product:8081
      - SPRING_DATASOURCE_USERNAME=categoryuser
      - SPRING_DATASOURCE_PASSWORD=eitooPhah4oosh2Eegh5xooy
    ports:
      - "8082:8082"
    networks:
      local_dev_net:
          aliases:
              - category

networks:
  local_dev_net:
    driver: bridge
